#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Kaia usb connection."
echo ""

sudo cp `sudo cp `ros2 pkg prefix kaia_bringup`/share/kaia_bringup/script/99-kaia-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger
